### ISSUE TITLE
Could you have description for your work?

### ISSUE THREAD

**Issue by zhangrong1722** [ytworks/ColorConstancy#1]
Hi!Your work is great after scaning your experiments results.But I feel confused for the following code.Could you attach an annotations?
`img_p3 = np.power(img.astype(np.float32), 3)`
`rgb_vec = np.power(np.mean(img_p3, (0, 1)), 1.0/3.0)`
`rgb_norm = np.sqrt(np.mean(np.power(rgb_vec, 2.0)))`
`rgb_vec = rgb_vec / rgb_norm`
 `rgb_vec = 1.0 / rgb_vec`
 `img = np.multiply(img.astype(np.float32), rgb_vec)`
Thanks.

**Comment by ytworks** [comment]
Add reference.
Please see it in detail.
